### ISSUE TITLE
thunk.call is not a function

### ISSUE THREAD

**Issue by Ilanak** [fisch0920/async-await-parallel#2]
When running the following code with node 8.2.1:
  const promiseArray = awsObjects.map(async function(obj) {
    if (await shouldUploadToADL(obj)) {
       await downloadFileFromS3(obj);
       await uploadFileToADL(obj.Key)
      }
  });

  await parallel(promiseArray, 5);

and i'm getting the following error:
thunk.call is not a function.

Nevermind , I found the issue!

**Comment by btisdall** [comment]
@Ilanak it would be helpful for others (like, er me :)) if you could describe what the issue was and how you fixed it.

**Comment by Ilanak** [comment]
@btisdall,  I think that I was missing a return right before the async (at the beginning of the map).
This code works for me:

        const promiseArray = awsObjects.map(key => {
          return async () => {
            try {
              if (await this.shouldUploadFile(redisModule, adlModule, key)) {
                await awsS3Module.downloadFileFromS3(key);
                // Upload File if it doesn't exist in ADL or if a new version of the file exists in S3
                await adlModule.uploadFileToAzureDataLake(key.Key);
                this.copyProperties.uploadedCount++;
                deleteFile(path.join(this.tempFolder, key.Key));
                // Update redis with the new file
                if (this.useRedis) {
                  await redisModule.addFileToRedis(key);
                }
              }
            } catch (ex) {
              winston.error(`error was thrown while working on element ${key.Key} ${ex}`);
            }
          };
        });

        try {
          await parallel(promiseArray, this.concurrencyNumber);
        } catch (ex) {
          winston.error(ex);
        }

**Comment by btisdall** [comment]
An extremely overdue thanks for this @Ilanak , that was the issue.
